server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shopsphere_orders
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.shopsphere.order_service.event.StockUpdateEvent

jwt:
  secret: oFwcn6TbbxvmRvTBEl7vif/On/PRFhUJs5HxQHjt0iw=